### ISSUE TITLE
Cannot install Android Auto 4.0.1 with CalendarSync 2.0.5

### ISSUE THREAD

**Issue by mobile-suit-taurran** [google/android-auto-companion-calendarsync-ios#1]
Hello,

I tried updating Android Auto Companion lib from version 3.2.1 to version 4.0.1. However I get an error with Calandar Sync v2.0.5 :
![CleanShot 2024-04-02 at 16 18 52@2x](https://github.com/google/android-auto-companion-calendarsync-ios/assets/10552996/f4237377-9bed-4a47-9ecb-2d626a95f890)

Will there be a new version of Calendar Sync compatible with Android Auto Companion 4.0.1 ?

Thank you in advance

**Comment by tapsns** [comment]
We have prerelease versions of both Calendar Sync (3.0.0) and Companion (4.0.1) for iOS that are compatible. The current plan is to mark them as release by end of this week pending QA. In your app you can change the dependency on Calendar Sync to 3.0.0 which should fix the problem.

**Comment by mobile-suit-taurran** [comment]
Thanks for your quick reply and info about the release !
